# Generated by Django 2.0.3 on 2018-03-25 13:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Apothecary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_level', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineDosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.TextField()),
                ('frequency', models.TextField()),
                ('period', models.TextField()),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_count', models.SmallIntegerField()),
                ('request_confirmation_time', models.DateTimeField()),
                ('apothecary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Apothecary')),
                ('medicine_dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineDosage')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(max_length=20)),
                ('pharmacy_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('token', models.TextField()),
                ('day_duration', models.SmallIntegerField(default=-1)),
                ('patient_age', models.PositiveSmallIntegerField()),
                ('medicine_card_number', models.CharField(max_length=10, null=True)),
                ('medicine_policy_number', models.CharField(max_length=16, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Doctor')),
            ],
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='medicine_request_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineRequestStatus'),
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineName'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineType'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='pharmacy',
            field=models.ManyToManyField(to='recipes.Pharmacy'),
        ),
        migrations.AddField(
            model_name='apothecary',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Pharmacy'),
        ),
        migrations.AddField(
            model_name='apothecary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
