# Generated by Django 2.0.3 on 2018-04-03 07:49

from django.db import migrations, models
import django.db.models.deletion
import recipes.managers


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20180330_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicinesPharmacies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', recipes.managers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pharmacy',
            field=models.ManyToManyField(through='recipes.MedicinesPharmacies', to='recipes.Pharmacy'),
        ),
        migrations.AddField(
            model_name='medicinespharmacies',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Medicine'),
        ),
        migrations.AddField(
            model_name='medicinespharmacies',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Pharmacy'),
        ),
    ]
