# Generated by Django 2.0.3 on 2018-04-08 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20180407_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedosage',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineName'),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='apothecary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Apothecary'),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='medicine_count',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinerequest',
            name='request_confirmation_time',
            field=models.DateTimeField(null=True),
        ),
    ]
