# Generated by Django 2.0.3 on 2018-04-08 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20180408_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinerequest',
            name='medicine_request_status',
        ),
        migrations.AddField(
            model_name='medicinerequest',
            name='given_medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Medicine'),
        ),
    ]
