# Generated by Django 2.0.3 on 2018-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20180408_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_level',
        ),
        migrations.AddField(
            model_name='medicinename',
            name='medicine_level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
