# Generated by Django 2.0.3 on 2018-05-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20180508_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
