# Generated by Django 2.0.3 on 2018-05-25 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_remove_medicinename_medicine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apothecary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='medicinename',
            name='medicine_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicinespharmacies',
            name='count',
            field=models.PositiveIntegerField(default=0, validators=[recipes.validators.validate_pos_value]),
        ),
        migrations.AlterField(
            model_name='medicinespharmacies',
            name='price',
            field=models.FloatField(default=0.0, validators=[recipes.validators.validate_pos_value]),
        ),
    ]
