# Generated by Django 2.2.4 on 2019-09-24 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20180525_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apothecary',
            options={'verbose_name': 'Аптекарь', 'verbose_name_plural': 'Аптекари'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Врач', 'verbose_name_plural': 'Врачи'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Больница', 'verbose_name_plural': 'Больницы'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Препорат', 'verbose_name_plural': 'Препораты'},
        ),
        migrations.AlterModelOptions(
            name='medicinename',
            options={'verbose_name': 'Название препората', 'verbose_name_plural': 'Названия препаратов'},
        ),
        migrations.AlterModelOptions(
            name='medicinerequest',
            options={'verbose_name': 'Запрос на лекарство', 'verbose_name_plural': 'Запросы на лекарства'},
        ),
        migrations.AlterModelOptions(
            name='medicinerequeststatus',
            options={'verbose_name': 'Статус заявки препората', 'verbose_name_plural': 'Статусы заявки препаратов'},
        ),
        migrations.AlterModelOptions(
            name='medicinetype',
            options={'verbose_name': 'Тип препората', 'verbose_name_plural': 'Типы препаратов'},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'verbose_name': 'Аптека', 'verbose_name_plural': 'Аптеки'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='apothecary',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Pharmacy', verbose_name='Аптека'),
        ),
        migrations.AlterField(
            model_name='apothecary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.Hospital', verbose_name='Больница'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineName', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.MedicineType', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='medicinename',
            name='medicine_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicinerequeststatus',
            name='status_name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='medicinetype',
            name='type_name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='pharmacy_name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Выписан'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='day_duration',
            field=models.PositiveIntegerField(default=15, verbose_name='Действительность рецепта (в днях)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Doctor', verbose_name='Врач'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='patient_age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст пациента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='patient_email',
            field=models.CharField(max_length=50, verbose_name='E-mail пациента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='patient_initials',
            field=models.CharField(max_length=100, verbose_name='ФИО пациента'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='token',
            field=models.TextField(verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
