# Generated by Django 2.2.4 on 2019-09-24 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20190924_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicinesPharmacies',
            new_name='Good',
        ),
        migrations.AlterField(
            model_name='apothecary',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
