# Generated by Django 2.2.4 on 2019-09-24 21:10

from django.db import migrations, models
import django.db.models.deletion
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20190924_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='good',
            name='count',
            field=models.PositiveIntegerField(default=0, validators=[recipes.validators.validate_pos_value], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='good',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Medicine', verbose_name='Лекарство'),
        ),
        migrations.AlterField(
            model_name='good',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Pharmacy', verbose_name='Аптека'),
        ),
        migrations.AlterField(
            model_name='good',
            name='price',
            field=models.FloatField(default=0.0, validators=[recipes.validators.validate_pos_value], verbose_name='Цена'),
        ),
        migrations.AlterUniqueTogether(
            name='good',
            unique_together={('medicine', 'pharmacy')},
        ),
    ]
